// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBReCi0Xhn0QoBZ6fqwXkeX6hppc-0EEwA',
    appId: '1:222929223513:web:be55d3200298e43e5c5648',
    messagingSenderId: '222929223513',
    projectId: 'vtproject2024-57545',
    authDomain: 'vtproject2024-57545.firebaseapp.com',
    storageBucket: 'vtproject2024-57545.firebasestorage.app',
    measurementId: 'G-D2C5DF9BWV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOup3nBCjzo7v0m2yT4G1ZIGwQcAaUEuw',
    appId: '1:222929223513:android:3b2b61e8a36686315c5648',
    messagingSenderId: '222929223513',
    projectId: 'vtproject2024-57545',
    storageBucket: 'vtproject2024-57545.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXkFM32XlbGhN9dqcIM8ZeXDItYKJm6-U',
    appId: '1:222929223513:ios:9becb920cc9554155c5648',
    messagingSenderId: '222929223513',
    projectId: 'vtproject2024-57545',
    storageBucket: 'vtproject2024-57545.firebasestorage.app',
    iosBundleId: 'com.example.pratikApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXkFM32XlbGhN9dqcIM8ZeXDItYKJm6-U',
    appId: '1:222929223513:ios:9becb920cc9554155c5648',
    messagingSenderId: '222929223513',
    projectId: 'vtproject2024-57545',
    storageBucket: 'vtproject2024-57545.firebasestorage.app',
    iosBundleId: 'com.example.pratikApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBReCi0Xhn0QoBZ6fqwXkeX6hppc-0EEwA',
    appId: '1:222929223513:web:6f5b6ecdbdcab9dd5c5648',
    messagingSenderId: '222929223513',
    projectId: 'vtproject2024-57545',
    authDomain: 'vtproject2024-57545.firebaseapp.com',
    storageBucket: 'vtproject2024-57545.firebasestorage.app',
    measurementId: 'G-9RXCFEGK0Y',
  );
}
